#!/usr/bin/env bash

search_query=$(dnf search "" | awk 'NR > 1 && $1 !~ /^[[:space:]]*$/ {print $1}' | fzf --height=70% --layout=reverse --border --prompt="Search Packages: ")

[ -z "$search_query" ] && exit 1

echo "Chosen: $search_query"

read -p "Install? (Y/n): " confirm

if [[ -z "$confirm" || "$confirm" =~ ^[Yy]$ ]]; then
    sudo dnf install "$search_query"
else
    echo "Operation canceled."
fi

