#!/usr/bin/env bash

search_query=$(pacman -Ss "" | grep -E '^\S+/\S+' | fzf --height=70% --layout=reverse --border \
  --preview 'pacman -Si $(echo {1} | cut -d"/" -f2) | head -n 10' --preview-window=right:50%,wrap --prompt="Search Packages: ")

[ -z "$search_query" ] && exit 1

package_name="$search_query"
package_name_simple=$(echo "$package_name" | cut -d'/' -f2)
echo "Chosen: $package_name_simple"
read -p "Install? (Y/n): " confirm

if [[ -z "$confirm" || "$confirm" =~ ^[Yy]$ ]]; then
    sudo pacman -S "$package_name_simple"
else
    echo "Operation canceled."
fi

